fifth_project/app/urls.py
from django.urls import path, include
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('special/', views.special, name='special')

]

fifth_project/fifth_project/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('app/', include('app.urls', namespace='app')),
    path('admin/', admin.site.urls),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special')
]

fifth_project/app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    portfolio = models.URLField(blank=True)
    # picture = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

fifth_project/app/forms.py
from django import forms
from app.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    portfolio = forms.URLField(required=False)
    # picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfileInfo
        fields = ('portfolio',)

fifth_project/app/views.py
from django.shortcuts import render
from app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'app/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("You are logged in!")


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save()
            profile.user = user

            # if 'picture' in request.FILES:
            #     profile.picture = request.FILES['picture']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'app/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == "POST":
        print(request)
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Accounts not active")
        else:
            print("Someone tried to login and failed!")
            print(f"Username: {username} and password: {password}")
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request, 'app/login.html', {})

fifth_project/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-static-top">
        <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'app:register' %}">Register</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'app:special' %}">Special Page</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'app:user_login' %}">Login</a></li>
                {% endif %}
           </ul>
        </div>
    </nav>
    {% block body_block %}
    {% endblock %}
</body>
</html>

fifth_project/templates/app/index.html
{% extends "app/base.html" %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1 style="text-align: center">Django Level Five</h1>
    </div>
</div>


{% endblock %}

fifth_project/templates/app/login.html
{% extends "app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <div class ="container">
        <h1>Please Login</h1>
        <form action="{% url 'app:user_login' %}" method="post">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">

            <label for="password">Password:</label>
            <input type="password" name="password">

            <input type="submit" value="Login">
        </form>
    </div>
</div>

{% endblock %}

fifth_project/templates/app/registration.html
{% extends "app/base.html" %}
{% load static %}

{% block body_block %}
<div class="container">
    <div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>

        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register">
        </form>
    {% endif %}
    </div>
</div>

{% endblock %}